#!/usr/bin/env python3
"""A python """
#
# **** DO NOT EDIT THIS FILE ****
# This file is managed by Ansible
# {{ ansible_managed }}
#
#*
#* File        :    create_server_config.py
#*
#* Description :    Script to create server configuration file use with naemon of the given server(s)
#*
#* Author   :   Luc Suryo <luc@suryo.com>
#*
#* Version  :   1.0a
#*
#* Date     :    Jun 2, 2026
#*
#* History  :
#* History  :
#*      Jul 10, 2019    LIS     First Release
#*      Aug 17, 2025    LIS     use of config.json and better server info
#*      Aug 18, 2025    LIS     add the -f flag so it  can use different config file
#*      May 27, 2026    LIS     support multiple servers
#*      Jun 2, 2026     LIS     add fw list in the config.json file
#*
#{%- raw %}

import os
import os.path
import sys
import signal
import json
import argparse
from time import strftime

# Colors Variables
colorOFF    = '\033[0m'
colorRed    = '\033[1;31m'
colorPurple = '\033[1;35m'
colorGreen  = '\033[1;32m'
colorYellow = '\033[1;33m'
colorBlue   = '\033[1;34m'
colorCyan   = '\033[1;36m'

__progname__    = os.path.basename(__file__)
__author__      = 'Luc Suryo'
__copyright__   = 'Copyright 2019 - ' + strftime('%Y') + ' © Badassops LLC'
__license__     = 'License 3-Clause BSD, https://opensource.org/licenses/BSD-3-Clause ♥'
__version__     = '1.0a'
__email__       = '<luc@suryo.com>'
__info__        = f'{__progname__} version: {__version__}\n{__copyright__}\nLicense' +\
                  f' {__license__}\nWritten by {__author__} {__email__}\n'
__usage_txt__   = '<-s servername> [-f | -h | -v | -d] \n\n' +\
                  f'{colorPurple}{__info__}{colorOFF}'
__description__ = 'Script to create server configuration file, use with naemon of the given server(s)'

# default values
_DRY_RUN = False

# wereto write the new configuration file
NEW_CFG_DIR  = 'new-cfg'

# the server info file and command info
srv_info_file  = 'servers.info'
cmd_info_file  = 'config.json'

# directories used
SRV_CFG_DIR    = './servers/'
DRY_RUN_DIR    = '/tmp/'

# global variable
cmd_dict      = {}
srv_dict      = {}
args_dict     = {}
fw_hosts      = []

# help text
_MULTI_HELP   = f'\n{colorBlue}Multiple separate by comma\'s.'
_SRVS_EXAMPLE = f'{colorYellow} Example: -s cyan,blue,red{colorOFF}'
_CFG_HELP     = f'{colorCyan}the configuration file to use,  default to {srv_info_file}.{colorOFF}'
_SRV_HELP     = f'{colorCyan}the server name, The given server name must exist in the ' +\
                f'file {srv_info_file} and has the correct format. {_MULTI_HELP}{_SRVS_EXAMPLE}'
_ALL_HELP     = f'{colorCyan}create all the servers configurations files{colorOFF}'
_DRY_RUN_HELP = f'{colorCyan}display the result on screen and delete the configuration file(s){colorOFF}'
_FORCE_HELP   = f'{colorCyan}force overwrite if the configuration file(s) already exist, default is false{colorOFF}'

def signalHandler(signum, frame):
    """Signal/interrupts handler
        @param  signum  {int}       The interrupt ID according to signal.h.
        @param  frame   {string}    Memory frame where the interrupted was called.
    """
    print(f'\n\n{colorYellow}Process aborted due to received an interrupt: {signum} {colorOFF}')

    if _DRY_RUN is True:
        print (f'\n\n{colorYellow}Frame: {frame}{colorOFF}')
    sys.exit(128 + signum)

def get_args():
    """get the given arguments
       @param       none
       return              dict with the set options
    """
    # Process giving arguments
    options = {}
    parser = argparse.ArgumentParser(usage = __usage_txt__, description = __description__,
        formatter_class = argparse.RawDescriptionHelpFormatter, conflict_handler='resolve')
    parser.add_argument('-v', '--version', action = 'version', version = __info__)
    group = parser.add_argument_group(f'{colorYellow}Required arguments one of these:' +\
                                      f' -s or -a. The arguments are mutual exclusion{colorOFF}')
    group = group.add_mutually_exclusive_group(required = True)
    group.add_argument('-c', '--config',   action = 'store',      dest = 'config',
        help = _CFG_HELP, default = srv_info_file)
    group.add_argument('-s', '--server',   action = 'store',      dest = 'name',
        help = _SRV_HELP, default = None)
    group.add_argument('-a', '--all',      action = 'store_true', dest = 'all',
        help = _ALL_HELP, default = False)
    parser.add_argument('--dry-run', '-d', action = 'store_true', dest = 'dry_run',
        help = _DRY_RUN_HELP, default = False)
    parser.add_argument('--force', '-f',   action = 'store_true', dest = 'force',
        help = _FORCE_HELP, default = False)
    options["server_name"]   = parser.parse_args().name
    options["server_all"]    = parser.parse_args().all
    options["force"]         = parser.parse_args().force
    options["dry_run"]       = parser.parse_args().dry_run
    options["server_config"] = parser.parse_args().config

    return options

def get_cmd_info():
    """Create the command dictionary
       @param       none
       return      the command dictionary
       exit        if failed
    """
    curr_cmd_dict = {}
    try:
        with open(cmd_info_file, 'r', encoding='utf-8') as file:
            curr_cmd_dict = json.load(file)
    except Exception as err:
        print(f'[ERR] - unable to read the data file {cmd_info_file} exception:{err}')
        sys.exit(2)

    return curr_cmd_dict

def get_servers_info():
    """Create the servers configuration
       @param       none
       return       dict with the setting of the servers
       exit        if failed
    """
    configure_hosts = {}
    all_cmds        = []
    try:
        with open(srv_info_file, 'r', encoding='utf-8') as server_info:
            data = server_info.readlines()

            for line in data:
                if (not line.startswith('#')) and (len(line.strip()) > 0):
                    host_id = line.strip().split(':')[0].rstrip('_')

                    if not host_id.startswith(tuple(fw_hosts)):
                        # none firewall servers
                        # get the dict keys
                        host_ip   = line.strip().split(':')[1].rstrip('_')
                        all_cmds  = list(line.strip().split(':')[2:])
                        host_cmds = []

                        for cmd in all_cmds:
                        # clean up list of cmd
                            if '_' not in cmd and cmd:
                                host_cmds.append(cmd)
                        configure_hosts[host_id] = {}
                        configure_hosts[host_id]["ip"] = host_ip
                        configure_hosts[host_id]["cmds"] = host_cmds
                    elif host_id in fw_hosts:
                        # firewall servers
                        host_cmds=[]
                        configure_hosts[host_id] = {}
                        host_ip  = line.strip().split(':')[1].rstrip('_')
                        all_cmds = list(line.strip().split(':')[2:])
                        host_cmds = []

                        for cmd in all_cmds:
                        # clean up list of cmd
                            if '_' not in cmd and cmd:
                                host_cmds.append(cmd)
                        configure_hosts[host_id]["ip"] = host_ip
                        configure_hosts[host_id]["cmds"] = host_cmds

    except Exception as err:
        print(f'[ERR] - unable to read the data from the file {srv_info_file} exception:{err}')
        sys.exit(2)

    return configure_hosts

def print_ansible_header(file_pointer):
    """Print the ansible header
       @paam        none
    """
    file_pointer.write('#\n')
    file_pointer.write('# **** DO NOT EDIT THIS FILE ****\n')
    file_pointer.write('# This file is managed by Ansible\n')
    file_pointer.write('# {{ ansible_managed }}\n')
    file_pointer.write('#\n\n')

def create_monitor_config(server_config, options):
    """Create the monitor configuration for the given server
       @param      server_config, dict with servers config that needs to be process
       exit        if failed
    """

    domain_name = cmd_dict["domain"]

    if domain_name:
        domain_name = domain_name + '.'
    host_template    = cmd_dict["host_template"]
    service_template = cmd_dict["service_template"]

    for key in server_config:
        # make sure the configuration does not exist unless a force overwrite (true) was given

        if options['dry_run']:
            cfg_file = DRY_RUN_DIR + key + ".cfg"
        else:
            cfg_file = SRV_CFG_DIR + key + ".cfg"

        if not options['force']:
            if os.path.isfile(cfg_file) is True:
                print(f'{colorRed}Configuration file {cfg_file} already exist, aborting...{colorOFF}\n')
                sys.exit(1)

        try:
            with open(cfg_file, 'w', encoding='utf-8') as fp:
                print_ansible_header(fp)
                fp.write('define host {\n')
                fp.write(f'  host_name            {key}{domain_name}\n')
                fp.write(f'  address              {server_config[key]['ip']}\n')
                fp.write(f'  use                  {host_template},host-pnp\n')
                fp.write('}\n\n')
                fp.write('define service {\n')
                fp.write(f'  use                  {service_template}\n')
                fp.write(f'  host_name            {key}{domain_name}\n')
                fp.write(f'  name                 {key}-service\n')
                fp.write('  register             0\n')
                # for future use
                # fp.write('# special for email and slack alering\n')
                # fp.write('define service {\n')
                # fp.write(f'  use                  {service_template}-email\n')
                # fp.write(f'  host_name            {key}{domain_name}\n')
                # fp.write(f'  name                 {key}-service-email\n')
                # fp.write('  register             0\n')
                # fp.write('}\n\n')
                # fp.write('# special no notification\n')
                # fp.write('define service {\n')
                # fp.write(f'  use                  {service_template}-no-notification\n')
                # fp.write(f'  host_name            {key}{domain_name}\n')
                # fp.write(f'  name                 {key}-service-no-notification\n')
                # fp.write('  register             0\n')
                fp.write('}\n\n')

                if key.startswith(tuple(fw_hosts)):
                    fp.write('# start netgate checks\n\n')
                else:
                    fp.write('# start checks\n\n')

                for srv_id in server_config[key]['cmds']:
                    # for future use
                    # for service only allowed on given servers

                    if 'cmd_allowed_hosts' in cmd_dict[srv_id]:
                        if key not in cmd_dict[srv_id]['cmd_allowed_hosts']:
                            continue
                    service_name = f'{key}-service'

                    if 'cmd_notification' in cmd_dict[srv_id] and \
                            cmd_dict[srv_id]['cmd_notification']:
                        service_name = f'{key}-service-no-notification'

                    if 'cmd_email' in cmd_dict[srv_id] and \
                            cmd_dict[srv_id]['cmd_email']:
                        service_name = f'{key}-service-service-email'

                    fp.write('define service {\n')

                    if cmd_dict[srv_id]['cmd_stats']:
                        fp.write(f'  use                  {service_name},service-pnp\n')
                    else:
                        fp.write(f'  use                  {service_name}\n')
                    fp.write(f'  service_description  {cmd_dict[srv_id]['cmd_info']}\n')
                    fp.write(f'  check_command        {cmd_dict[srv_id]['cmd_name']}\n')
                    # for future use
                    # write service with handler

                    if 'cmd_handler' in cmd_dict[srv_id]:
                        fp.write(f'  event_handler        {cmd_dict[srv_id]['cmd_event_handler']}\n')

                        if 'cmd_max_check_attempts' in cmd_dict[srv_id]:
                            fp.write(f'  max_check_attempts   {cmd_dict[srv_id]['cmd_max_check_attempts']}\n')

                        if 'cmd_check_interval' in cmd_dict[srv_id]:
                            fp.write(f'  check_interval       {cmd_dict[srv_id]['cmd_check_interval']}\n')
                    fp.write('  register             1\n')
                    fp.write('}\n\n')

            if options['dry_run']:
                try:
                    with open(cfg_file, 'r', encoding='utf-8') as dfp:
                        content = dfp.read()
                    print(f'{content}')
                except Exception as e:
                    print(f'{colorRed}An error occurred reading the file {cfg_file}: {e}{colorOFF}')
                os.remove(cfg_file)
        except Exception as err:
            print(f'{colorRed}Error create the file {key}.cfg, error : {err}{colorOFF}')
            sys.exit(1)

def check_srv_value(srv_value):
    """ check if the given server of gs name are valid
       @param     srv_value string  value to be check server
                                    can be multiple value
       exit 1     if the there is a invalid server name
       return     list of servers
    """
    error = 0
    server_list = []
    # checking servers

    for value in srv_value.split(','):
        if value not in srv_dict:
            print(f'{colorRed}Given server {colorBlue}{value}{colorRed}' +\
                  f' has no configuration.{colorOFF}')
            error = 1
        server_list.append(value)

    if error == 1:
        print(f'{colorRed}Aborting...{colorOFF}')
        sys.exit(1)

    return server_list

def create_srv_dict(servers):
    """ create a dict of the given server
       @param     srv_value string  value to be check server name
                                    can be multiple value
       exit 1     if the there is a invalid server name
       return     dict of the given servers with their cmd config
    """
    new_srv_dict = {}

    for server in servers:
        new_srv_dict[server] = srv_dict[server]

    return new_srv_dict

if __name__ == "__main__":
    # Install signal/interrupts handler, we capture only SIGHUP, SIGINT, SIGKILL and TERM
    signal.signal(signal.SIGHUP, signalHandler)
    signal.signal(signal.SIGINT, signalHandler)
    signal.signal(signal.SIGTERM, signalHandler)

    args_dict     = get_args()
    srv_info_file = args_dict["server_config"]
    srv_dict      = get_servers_info()
    cmd_dict      = get_cmd_info()
    fw_hosts      = cmd_dict['fw_hosts']
    servers_list  = []
    srv           = {}

    if args_dict["server_all"]:
        srv = srv_dict
        create_monitor_config(srv, args_dict)
        sys.exit(0)
    else:
        if args_dict['server_name'] is not None:
            servers_list = check_srv_value(args_dict["server_name"])
        print(f'{create_srv_dict(servers_list)}')
    #create_monitor_config(create_srv_dict(servers_list), args_dict)
    sys.exit(0)
#{%- endraw %}
